version: '3'

services:
    ##################################################################
    frontend-fpm:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
          - ./frontend/:/var/www/
        links:
          - service1-nginx:service1
          - service2-nginx:service2
          - service3-nginx:service3
        environment: 
          - SERVICE1_HOST=service1
          - SERVICE2_HOST=service2
          - SERVICE3_HOST=service3
    frontend-nginx:
        build:
            context: ./frontend/docker/nginx
            dockerfile: Dockerfile
        volumes:
          - ./frontend/docker/nginx/default.local.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "8080:80"
        links:
          - frontend-fpm:app
    ##################################################################
    service1-fpm:
        build:
            context: ./service1
            dockerfile: Dockerfile
        volumes:
          - ./service1/:/var/www/
    service1-nginx:
        build:
            context: ./service1/docker/nginx
            dockerfile: Dockerfile
        volumes:
          - ./service1/docker/nginx/default.local.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "8081:80"
        links:
          - service1-fpm:app
    ##################################################################
    service2-fpm:
        build:
            context: ./service2
            dockerfile: Dockerfile
        volumes:
          - ./service2/:/var/www/
    service2-nginx:
        build:
            context: ./service2/docker/nginx
            dockerfile: Dockerfile
        volumes:
          - ./service2/docker/nginx/default.local.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "8082:80"
        links:
          - service2-fpm:app
    ##################################################################
    service3-fpm:
        build:
            context: ./service3
            dockerfile: Dockerfile
        volumes:
          - ./service3/:/var/www/
    service3-nginx:
        build:
            context: ./service3/docker/nginx
            dockerfile: Dockerfile
        volumes:
          - ./service3/docker/nginx/default.local.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "8083:80"
        links:
          - service3-fpm:app
